### ISSUE TITLE
duplicate entry

### ISSUE THREAD

**Issue by ygwane** [csuka/ansible_role_percona_xtradb_cluster#3]
https://github.com/csuka/ansible_role_percona_xtradb_cluster/blob/97ed83465b5308b6cb0e60f8a93c593c660fd818/templates/mysqld.cnf.j2#L62

same line on L60

**Comment by ygwane** [comment]
https://github.com/csuka/ansible_role_percona_xtradb_cluster/blob/97ed83465b5308b6cb0e60f8a93c593c660fd818/templates/mysqld.cnf.j2#L72

same line on L65

**Comment by csuka** [comment]
fixed.
