### ISSUE TITLE
Question about backup script

### ISSUE THREAD

**Issue by wally007** [csuka/ansible_role_percona_xtradb_cluster#4]
Hello,

first of all thank you for haring very comprehensive deployment role. I used it as an inspiration to write more fail-safe playbooks as well.

I wanted to ask for clarification on `db_backup.sh` script. Why did you decide to dump each table into separate sql file?
As far as I can tell, mysql_db module does not allow table import of the tables, so there is no way to use ansible to rebuild the database (short of using shell module)

I've modified the script and I'm going to try to write a role to deploy/restore databases, so it is not an issue for me.
However, I wanted to ask whether I missed something or how are you restoring your databases using ansible ?

**Comment by csuka** [comment]
> Why did you decide to dump each table into separate sql file?

'Cause it's quite handy actually, it provides a lot of flexibility for multiple of reasons.

> mysql_db module does not allow table import of the tables, so there is no way to use ansible to rebuild the database (short of using shell module)

When one wants to restore, I don't expect them to use Ansible to do it.  
Restoring is a last resort in case of fuck-ups. So yes, I expect the engineers to simply use bash/shell.  
I've never designed this role to restore databases/tables.

>  I wanted to ask whether I missed something or how are you restoring your databases using ansible ?
Nope :)

**Comment by wally007** [comment]
ok thanks. 
I want to remove as many manual steps from administrator as possible and automate restore process as well.
Thank you for the inspiration.
